### PR TITLE
Angular frontend and  user controllers

### PR DESCRIPTION
**Pull request by annanodiyo**

### CODE REVIEW

**Review by stevehotcodes — CHANGES_REQUESTED** [review]
there are some conflicts in the index.ts and  index.js . 
Kindly gitignore your dist folder in your end . You can do this by 
: 
adding the dist folder for the file to be ignored in the backend folder

**Comment by stevehotcodes** [comment]
Gitignore the dist folder in your  backend and then commit and push the changes again.

**Comment by annanodiyo** [comment]
added dist to gitignore

**Review by stevehotcodes — COMMENTED** [review]
okay

**Review by stevehotcodes — APPROVED** [review]

**Pull request merged**
