### PR TITLE
Order , Sales ,and Cart Feature

### PR DESCRIPTION
**Pull request by stevehotcodes**
- added stored procedures
-added controllers

### CODE REVIEW

**Review by annanodiyo — CHANGES_REQUESTED** [review]
maybe you can use product_id instead of id

**Comment by annanodiyo** [comment]
check the changes requested

**Comment by stevehotcodes** [comment]
the reason I have used the id is that when you use product_id in the product table it maybe  difficult to determine whether it is the primary key or foreign key. When I name the field as "id"  in the product table it mainly references the primary key of that table and it distinguishes the product id used in the other tables like cart , and order tables.

**Comment by annanodiyo** [comment]
that's ok

**Review by annanodiyo — APPROVED** [review]
seen

**Pull request merged**
